name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker-compose build

    - name: Start containers
      run: docker-compose up -d

    - name: Wait for application to start
      run: sleep 10

    - name: Check if application is running
      run: |
        curl -f http://localhost:8080 || exit 1

    - name: Run basic health check
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
        if [ $response -eq 200 ]; then
          echo "Application is healthy"
        else
          echo "Application health check failed with status: $response"
          exit 1
        fi

    - name: Stop containers
      run: docker-compose down

    - name: Display logs on failure
      if: failure()
      run: docker-compose logs
